label_list = ['O', 'I-DATE', 'B-DATE', 'E-DATE',
              'I-LOC', 'B-LOC', 'E-LOC',
              'I-MONEY', 'B-MONEY', 'E-MONEY',
              'I-ORG', 'B-ORG', 'E-ORG',
              'I-PER', 'B-PER', 'E-PER',
              'I-PERCENT', 'B-PERCENT', 'E-PERCENT',
              'I-TIME', 'B-TIME', 'E-TIME',
              'I-WOA', 'B-WOA', 'E-WOA',
              'I-EVE', 'B-EVE', 'E-EVE',
              'I-FAC', 'B-FAC', 'E-FAC',
              'I-DUC', 'B-DUC', 'E-DUC',
              'I-ANG', 'B-ANG', 'E-ANG',
              'B-HLOC', 'I-HLOC', 'E-HLOC',
              'B-NLOC', 'I-NLOC', 'E-NLOC',
              'B-ROOMS', 'I-ROOMS', 'E-ROOMS',
              'B-MONEY-TYPE', 'I-MONEY-TYPE', 'E-MONEY-TYPE',
              'B-CAPACITY', 'I-CAPACITY', 'E-CAPACITY',
              'B-DURATION', 'I-DURATION', 'E-DURATION']
label_encoding_dict = {'O': 0, 'B-DATE': 1, 'I-DATE': 2, 'E-DATE': 3,
                       'B-LOC': 4, 'I-LOC': 5, 'E-LOC': 6,
                       'B-MONEY': 7, 'I-MONEY': 8, 'E-MONEY': 9,
                       'B-ORG': 10, 'I-ORG': 11, 'E-ORG': 12,
                       'B-PER': 13, 'I-PER': 14, 'E-PER': 15,
                       'B-PERCENT': 16, 'I-PERCENT': 17, 'E-PERCENT': 18,
                       'B-TIME': 19, 'I-TIME': 20, 'E-TIME': 21,
                       'B-WOA': 22, 'I-WOA': 23, 'E-WOA': 24,
                       'B-EVE': 25, 'I-EVE': 26, 'E-EVE': 27,
                       'B-FAC': 28, 'I-FAC': 29, 'E-FAC': 30,
                       'B-DUC': 31, 'I-DUC': 32, 'E-DUC': 33,
                       'B-ANG': 34, 'I-ANG': 35, 'E-ANG': 36,
                       'B-HLOC': 37, 'I-HLOC': 38, 'E-HLOC': 39,
                       'B-NLOC': 40, 'I-NLOC': 41, 'E-NLOC': 42,
                       'B-ROOMS': 43, 'I-ROOMS': 44, 'E-ROOMS': 45,
                       'B-MONEY-TYPE': 46, 'I-MONEY-TYPE': 47, 'E-MONEY-TYPE': 48,
                       'B-CAPACITY': 49, 'I-CAPACITY': 50, 'E-CAPACITY': 51,
                       'B-DURATION': 52, 'I-DURATION': 53, 'E-DURATION': 54}
intent_to_encoding = {'renting': 0, 'looking': 1, 'replace': 2, 'JUNK': 3}

inversed_label_encoding_dict = {v: k for k, v in label_encoding_dict.items()}
